/**
 * Recommendation Engine Configuration
 *
 * All tunable parameters for the perfume recommendation system.
 * Change values here to adjust filtering thresholds, scoring weights,
 * and fuzzy matching behavior without modifying algorithm code.
 */

export const RECOMMENDATION_CONFIG = {
  // --- Minimum Match Gate ---
  // Dynamic threshold: Math.max(1, Math.ceil(perfume.mainNotes.length * ratio))
  // Default ratio = 0.6, fallback ratio = 0.4
  MIN_MATCH_RATIO: 0.6,
  MIN_MATCH_RATIO_FALLBACK: 0.4,

  // --- Scoring Weights (must sum to 100) ---
  SCORE_WEIGHTS: {
    notePosition: 35,     // Note match + tier/position weighting
    categoryAffinity: 15, // Note family/category overlap
    season: 15,           // Season suitability
    intensity: 10,        // Intensity/longevity match
    genderMatch: 10,      // Gender exact match
    inspiredBonus: 5,     // Inspired-by luxury brand bonus
    richProfile: 5,       // Rich note profile (≥6 notes)
    crowdFavorite: 5,     // Bestseller / crowd favorite bonus
  } as const,

  // --- Tier Weights ---
  // How much each note tier contributes (top notes are most prominent)
  TIER_WEIGHTS: {
    top: 1.0,
    middle: 0.6,
    base: 0.3,
  } as const,

  // --- Output Thresholds ---
  MIN_TOTAL_SCORE: 20,        // Minimum score to appear in results
  MAX_RESULTS: 6,             // How many perfumes to return
  RICH_PROFILE_THRESHOLD: 6,  // Min total notes for rich profile bonus
  MIN_GUARANTEED_RESULTS: 3,  // Always return at least this many recommendations

  /** Product slugs omitted from quiz recommendations (still in catalog JSON). */
  EXCLUDED_PERFUME_SLUGS: [] as string[],

  // --- Confidence Tiers ---
  CONFIDENCE_HIGH_THRESHOLD: 45,    // Score ≥ 45 → "high" confidence
  CONFIDENCE_MEDIUM_THRESHOLD: 25,  // Score ≥ 25 → "medium" confidence

  // --- Bestseller IDs ---
  // Add product IDs here when sales data is available.
  // If empty, all perfumes get a neutral score (2 pts).
  BESTSELLER_IDS: [] as string[],

  // --- Season Inference from Note Categories ---
  // Used when user doesn't specify a season preference.
  SEASON_INFERENCE: {
    FRESH_CITRUS: { 'summer-spring': 0.8, 'all': 0.5 },
    TROPICAL: { 'summer-spring': 0.9, 'all': 0.3 },
    SWEET_GOURMAND: { 'fall-winter': 0.7, 'all': 0.6 },
    GREEN: { 'summer-spring': 0.7, 'all': 0.5 },
    WARM_SPICY: { 'fall-winter': 0.8, 'all': 0.5 },
    MUSKY_AMBER: { 'fall-winter': 0.7, 'all': 0.6 },
    FLORAL: { 'summer-spring': 0.6, 'all': 0.6 },
    AQUATIC: { 'summer-spring': 0.9, 'all': 0.2 },
    FRUITY: { 'summer-spring': 0.7, 'all': 0.5 },
  } as Record<string, Record<string, number>>,

  // --- Synonym Map ---
  // Maps alternate spellings/names to a canonical form for fuzzy matching.
  // IMPORTANT: Canonical forms must match the strings used in perfumes.json.
  // The fuzzy matcher handles case-insensitive + substring + Levenshtein,
  // so the synonym map only needs to handle true alternate names.
  SYNONYM_MAP: {
    // Alternate spellings / typos in perfume data
    'marine notes': 'water notes',
    'ba7r': 'marine notes',
    'watery notes': 'water notes',
    'sea notes': 'marine notes',
    'aquatic notes': 'water notes',
    'ocean': 'marine notes',
    'pinapple': 'pineapple',
    'woods': 'wood notes',
    'woods notes': 'wood notes',
    'woodsy': 'wood notes',
    'woody': 'wood notes',
    'oud wood': 'oud',
    'oud agarwood': 'oud',
    'tonka': 'tonka beans',
    'tonka bean': 'tonka beans',
    'whiskey': 'cognac',
    'chocolate': 'cacao',
    'cocoa': 'cacao',
    'cocoa butter': 'cacao',
    'bourbon vanilla': 'vanilla',
    'vanille': 'vanilla',
    'madagascar vanilla': 'vanilla',
    'vanilla absolute': 'vanilla',
    'vanilla caviar': 'vanilla',
    'rose': 'turkish rose',
    'natural oud agarwood': 'oud',
    'strawberries': 'strawberry',
    'bergamot orange': 'bergamot',
    'pineapple coconut': 'pineapple',
    'rum': 'white rum',
    'brandy': 'white rum',
    'juniper berries': 'juniper',
    'chinese tea': 'tea',
    'black tea': 'tea',
    'beach': 'beach notes',
    'tropical fruits': 'tropical fruits',
    'tropical': 'tropical fruits',
    'apple': 'green apple',
    'red apple': 'green apple',
    'frozen apple': 'green apple',
    'peppermint': 'mint',
    'spearmint': 'mint',
    'black currant': 'blackcurrant',
    'black currant leaf': 'blackcurrant',
    'lychee': 'litchi',
    'whipped cream': 'cream',
    'creamy milk': 'milk',
    'cotton candy': 'sugar',
    'brown sugar': 'sugar',
    'sugar cane': 'sugar',
    'ice cream': 'vanilla',
    'bubblegum': 'strawberry',
    'maple': 'caramel',
    'peru balsam': 'balsam',
    'tolu balsam': 'balsam',
    'ambergris': 'amber',
    'ambroxan': 'amber',
    'iso e super': 'amber',
    'cashmeran': 'musk',
    'white musk': 'musk',
    'skin musk': 'musk',
    'muscone': 'musk',
    'egyptian musk': 'musk',
    'clean musk': 'musk',
    'powdery musk': 'musk',
    'animalic musk': 'musk',
    'synthetic musk': 'musk',
    'musk tahara': 'musk',
    'black musk': 'musk',
    'civet': 'musk',
    'castoreum': 'leather',
    'birch tar': 'leather',
    'ashes': 'leather',
    'smoke': 'leather',
    'beeswax': 'honey',
    'coumarin': 'tonka beans',
    'styrax': 'benzoin',
    'opoponax': 'labdanum',
    'myrrh': 'labdanum',
    'driftwood': 'wood notes',
    'teakwood': 'wood notes',
    'rosewood': 'wood notes',
    'ebony': 'wood notes',
    'mahogany': 'wood notes',
    'bamboo wood': 'wood notes',
    'oakwood': 'wood notes',
    'pine': 'cedar',
    'cypress': 'cedar',
    'nutmeg': 'spices',
    'coriander': 'spices',
    'clove': 'spices',
    'bay leaf': 'spices',
    'paprika': 'spices',
    'chili': 'spices',
    'wasabi': 'spices',
    'star anise': 'spices',
    'peony': 'turkish rose',
    'magnolia': 'white flowers',
    'gardenia': 'white flowers',
    'tuberose': 'white flowers',
    'lily of the valley': 'white flowers',
    'freesia': 'white flowers',
    'frangipani': 'white flowers',
    'cherry blossom': 'turkish rose',
    'hibiscus': 'turkish rose',
    'osmanthus': 'apricot',
    'neroli': 'orange blossom',
    'ylang': 'jasmine',
    'honeysuckle': 'jasmine',
    'carnation': 'spices',
    'iris': 'violet',
    'ozone': 'amber',
    'green tea': 'tea',
    'elemi': 'incense',
    'almond': 'almond',
    'hazelnut': 'almond',
    'coconut milk': 'coconut',
    'cannabis': 'hemp',
    'absinthe': 'wormwood',
    'carrot seeds': 'carrot',
    'davana': 'herbal',
    'cassis': 'blackcurrant',
    'seaweed': 'marine notes',
    'laurel': 'herbal',
    'fig leaf': 'fig',
    'rhubarb': 'fruits',
    'date': 'fruits',
    'banana': 'fruits',
    'kiwi': 'fruits',
    'melon': 'fruits',
    'passion fruit': 'passionfruit',
    'morello cherry': 'cherry',
    'wild strawberry': 'strawberry',
    'red fruits': 'fruits',
    'dried fruits': 'fruits',
    'licorice': 'spices',
    'caraway': 'spices',
    'allspice': 'spices',
    'bell pepper': 'spices',
    'red pepper': 'spices',
    'ceylon cinnamon': 'cinnamon',
    'fresh ginger': 'ginger',
    'bakhoor': 'incense',
    'agarwood': 'oud',
    'damask rose': 'turkish rose',
    'taif rose': 'turkish rose',
    'suede': 'leather',
    'whisky absolute': 'cognac',
    'birch': 'wood notes',
    'sage': 'herbal',
    'clary sage': 'herbal',
    'rosemary': 'herbal',
    'basil': 'herbal',
    'ambrette': 'musk',
    'truffle': 'earthy',
    'chestnut': 'earthy',
    'cookie': 'gourmand',
    'waffle': 'gourmand',
    'biscuit': 'gourmand',
    'toffee': 'caramel',
    'praline': 'almond',
    'cream': 'milk',
    'caramelized popcorn': 'caramel',
    'mexican chocolate': 'cacao',
    'bitter almond': 'almond',
    'nuts': 'almond',
    'coconut': 'coconut',
    'cocunut': 'coconut',
    'cocoanut': 'coconut',
    'coco nut': 'coconut',
    'caramel': 'caramel',
    'carmel': 'caramel',
    'vanila': 'vanilla',
    'vaniilla': 'vanilla',
    'vanila caviar': 'vanilla caviar',
    'bergamont': 'bergamot',
    'sandelwood': 'sandalwood',
    'sandal': 'sandalwood',
    'patchouly': 'patchouli',
    'pachouli': 'patchouli',
    'musks': 'musk',
    'amber wood': 'amber',
    'rose wood': 'wood notes',
    'lavendar': 'lavender',
    'jasmin': 'jasmine',
    'ylang ylang': 'ylang',
    'citris': 'citrus',
    'beregmont': 'bergamot',
    'marshmallow': 'marshmallow',
    'coffee': 'coffee',
    'honey': 'honey',
    'sugar': 'sugar',
    'white rum': 'white rum',
    'cognac': 'cognac',
    'milk': 'milk',
    'ginger': 'ginger',
    'cinnamon': 'cinnamon',
    'cardamom': 'cardamom',
    'saffron': 'saffron',
    'pink pepper': 'pink pepper',
    'black pepper': 'pepper',
    'bergamot': 'bergamot',
    'lemon': 'lemon',
    'lime': 'citron',
    'grapefruit': 'grapefruit',
    'mandarin': 'mandarin',
    'orange': 'orange',
    'tangerine': 'mandarin',
    'citron': 'citron',
    'green apple': 'green apple',
    'pear': 'pear',
    'peach': 'peach',
    'apricot': 'apricot',
    'plum': 'plum',
    'cherry': 'cherry',
    'raspberry': 'raspberry',
    'strawberry': 'strawberry',
    'blackberry': 'blackberry',
    'blackcurrant': 'blackcurrant',
    'passionfruit': 'passionfruit',
    'mango': 'mango',
    'pineapple': 'pineapple',
    'litchi': 'litchi',
    'fig': 'fig',
    'vanilla': 'vanilla',
    'turkish rose': 'turkish rose',
    'jasmine': 'jasmine',
    'lavender': 'lavender',
    'geranium': 'geranium',
    'violet': 'violet',
    'lily': 'white flowers',
    'orchid': 'white flowers',
    'oud': 'oud',
    'sandalwood': 'sandalwood',
    'cedar': 'cedar',
    'cedarwood': 'cedar',
    'patchouli': 'patchouli',
    'vetiver': 'vetiver',
    'amber': 'amber',
    'musk': 'musk',
    'leather': 'leather',
    'tobacco': 'tobacco',
    'incense': 'incense',
    'oakmoss': 'oakmoss',
    'mint': 'mint',
    'tea': 'tea',
    'white flowers': 'white flowers',
    'wood notes': 'wood notes',
    'spices': 'spices',
    'herbal': 'herbal',
    'fruits': 'fruits',
    'gourmand': 'gourmand',
    'earthy': 'earthy',
    'balsam': 'balsam',
    'benzoin': 'benzoin',
    'labdanum': 'labdanum',
    'pepper': 'pepper',
    'beach notes': 'beach notes',
    'mixed berries': 'berries',
    'berries': 'berries',
  } as Record<string, string>,

  // --- Fuzzy Matching ---
  LEVENSHTEIN_MAX_SHORT: 2,   // Max Levenshtein distance for words ≤6 chars
  LEVENSHTEIN_MAX_LONG: 3,    // Max Levenshtein distance for words >6 chars
  SHORT_WORD_THRESHOLD: 6,    // Word length threshold for short/long categorization
} as const;

export type RecommendationConfig = typeof RECOMMENDATION_CONFIG;
